# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ntomic/trixie"
  config.vm.box_version = "1.0.0"

  config.vm.network("private_network", ip: "192.168.56.22")

  config.vm.provider("virtualbox") do |v|
    v.memory = 8192
    v.cpus = 4
  end
end
