---
- name: Install Kafka and add to PATH
  hosts: kafka
  become: true
  vars:
    # Download variables
    kafka_url: "https://downloads.apache.org/kafka/4.3.1/kafka_2.13-4.3.1.tgz"
    kafka_archive: "/tmp/kafka.tgz"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - openjdk-21-jdk
          - unzip
          - tar
          - wget
          - rsync
          - net-tools
          - jq
        state: present
        update_cache: true

    - name: Create Kafka directory
      ansible.builtin.file:
        path: "{{ kafka }}"
        state: directory
        mode: "0755"
        owner: vagrant
        group: vagrant

    - name: Extract Kafka archive
      ansible.builtin.unarchive:
        src: "{{ kafka_url }}"
        dest: "{{ kafka }}"
        remote_src: true
        mode: "0755"
        owner: vagrant
        group: vagrant
        creates: "{{ kafka_bin }}"
        extra_opts:
          - --strip-components=1

    - name: Add Kafka to PATH
      ansible.builtin.copy:
        dest: /etc/profile.d/kafka.sh
        content: |
          export PATH={{ kafka_bin }}:$PATH
        mode: "0755"


- name: Configure key store for SSL
  hosts: kafka
  vars:
    keystore: /opt/keytool
    keystorefile: '{{ keystore }}/keystore.pkcs12'
    keystorepassword: "donau333"

  tasks:
    - name: Remove keytool directory
      become: true
      file:
        path: '{{ keystore }}'
        state: absent

    - name: Create keytool directory
      become: true
      file:
        path: '{{ keystore }}'
        state: directory
        mode: '0755'
        owner: vagrant
        group: vagrant

    - name: Generate key pair for each broker
      command:
        argv:
          - keytool
          - -keystore
          - '{{ keystorefile }}'
          - -storepass
          - '{{ keystorepassword }}'
          - -genkeypair
          - -alias
          - ' {{ inventory_hostname }}'
          - -validity
          - 360
          - -keyalg
          - RSA
          - -dname
          - CN=Nemanja Tomic, OU=CommitFlow, O=Nemanja Tomic, L=Blumberg, ST=Baden-Württemberg, C=DE
          - -storetype
          - pkcs12
        creates: '{{ keystorefile }}'
