node.id=2
log.dirs=/home/vagrant/kafka/data
listeners=PLAINTEXT://:9093,CONTROLLER://:9193
process.roles=broker,controller
controller.quorum.voters=1@192.168.56.11:9192,2@192.168.56.12:9192,3@192.168.56.13:9192
controller.listener.names=CONTROLLER
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
