---
- name: Install and configure Neovim
  hosts: all

  vars:
    nvim_archive: nvim-linux-x86_64.tar.gz
    nvim_url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
    nvim_install_dir: /opt/nvim-linux-x86_64
    nvim_config_src: /home/nemo/.config/nvim

    go_version: 1.26.3
    go_checksum: 2b2cfc7148493da5e73981bffbf3353af381d5f93e789c82c79aff64962eb556

  tasks:
    - name: Install apt dependencies
      become: true
      ansible.builtin.apt:
        name:
          - rsync
          - git
          - luarocks
          - python3-pip
          - npm
          - ruby-full
          - php
          - composer
          - default-jdk
          - ripgrep
          - fd-find
          - tree-sitter-cli
        update_cache: true
        cache_valid_time: 3600

    - name: Check if nvim is already installed
      ansible.builtin.stat:
        path: "{{ nvim_install_dir }}/bin/nvim"
      register: nvim_installed

    - name: Install Neovim
      when: not nvim_installed.stat.exists
      block:
        - name: Download Neovim archive
          ansible.builtin.get_url:
            url: "{{ nvim_url }}"
            dest: "/tmp/{{ nvim_archive }}"
            mode: '0644'

        - name: Remove existing Neovim directory
          ansible.builtin.file:
            path: "{{ nvim_install_dir }}"
            state: absent

        - name: Extract Neovim archive
          become: true
          ansible.builtin.unarchive:
            src: "/tmp/{{ nvim_archive }}"
            dest: /opt
            remote_src: true

    - name: Add Neovim to global PATH
      become: true
      ansible.builtin.copy:
        dest: /etc/profile.d/nvim.sh
        content: 'export PATH="/opt/nvim-linux-x86_64/bin:$PATH"'
        mode: '0755'

    - name: Ensure Neovim config parent directory exists
      ansible.builtin.file:
        path: /home/vagrant/.config
        state: directory
        mode: '0755'

    - name: Sync Neovim configuration
      ansible.posix.synchronize:
        src: "{{ nvim_config_src }}/"
        dest: /home/vagrant/.config/nvim
        delete: true

    - name: Install Rust (rustup)
      ansible.builtin.shell: |
        set -o pipefail
        curl https://sh.rustup.rs -sSf | sh -s -- -y
      args:
        creates: /home/vagrant/.cargo/bin/cargo

    - name: Add cargo to global PATH
      become: true
      ansible.builtin.copy:
        dest: /etc/profile.d/rust.sh
        content: 'export PATH="/home/vagrant/.cargo/bin:$PATH"'
        mode: "0755"

    - name: Download Go
      ansible.builtin.get_url:
        url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: /tmp/go.tar.gz
        mode: "0644"
        checksum: "sha256:{{ go_checksum }}"

    - name: Extract Go
      become: true
      ansible.builtin.unarchive:
        src: /tmp/go.tar.gz
        dest: /usr/local
        remote_src: true
      args:
        creates: /usr/local/go

    - name: Add Go to PATH
      become: true
      ansible.builtin.copy:
        dest: /etc/profile.d/go.sh
        content: |
          export PATH=$PATH:/usr/local/go/bin
          export PATH=$PATH:/home/vagrant/go/bin
        mode: "0555"

    - name: Install Julia
      ansible.builtin.shell: |
        set -o pipefail
        curl -fsSL https://install.julialang.org | sh -s -- -y
      args:
        creates: /home/vagrant/.juliaup/bin/julia


- name: Install Docker
  hosts: all
  become: true

  tasks:
    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker repository
      ansible.builtin.shell: |
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
        https://download.docker.com/linux/debian \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
        > /etc/apt/sources.list.d/docker.list
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Create docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add docker group to user
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: true

    - name: Ensure docker.service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true


- name: Install Kafka and add to PATH
  hosts: all

  vars:
    # Download variables
    kafka_url: https://downloads.apache.org/kafka/4.2.0/kafka_2.13-4.2.0.tgz
    kafka_archive: kafka_2.13-4.2.0.tgz

    # Installation path
    kafka: /home/vagrant/kafka
    kafka_install_dir: "{{ kafka }}/kafka_2.13-4.2.0"
    kafka_bin: "{{ kafka_install_dir }}/bin"

  tasks:
    - name: Install apt dependencies
      become: true
      ansible.builtin.apt:
        name:
          - default-jdk
        update_cache: true
        cache_valid_time: 3600

    - name: Create ~/kafka folder
      ansible.builtin.file:
        path: "{{ kafka }}"
        state: directory
        mode: "0700"

    - name: Check if Kafka is already installed
      ansible.builtin.stat:
        path: "{{ kafka_install_dir }}"
      register: kafka_installed

    - name: Download Kafka archive
      ansible.builtin.get_url:
        url: "{{ kafka_url }}"
        dest: "/tmp/{{ kafka_archive }}"
        mode: "0700"
      when: not kafka_installed.stat.exists

    - name: Extract Kafka archive
      ansible.builtin.unarchive:
        src: "/tmp/{{ kafka_archive }}"
        dest: "{{ kafka }}"
        remote_src: true
      when: not kafka_installed.stat.exists

    - name: Add Kafka to PATH
      become: true
      ansible.builtin.copy:
        dest: /etc/profile.d/kafka.sh
        content: 'export PATH={{ kafka_bin }}:"$PATH"'
        mode: "0444"


- name: Configure standalone Kafka broker
  hosts: all

  vars:
    kafka: /home/vagrant/kafka
    kafka_cluster_id: "{{ kafka }}/cluster.id"
    kafka_logs: "{{ kafka }}/logs"

    kafka_install_dir: "{{ kafka }}/kafka_2.13-4.2.0"
    kafka_bin: "{{ kafka_install_dir }}/bin"

    kafka_config: /vagrant/kafka/server.properties

  tasks:
    - name: Check if cluster ID exists
      ansible.builtin.stat:
        path: "{{ kafka_cluster_id }}"
      register: cluster_id_file

    - name: Generate Kafka cluster ID if not exist
      when: not cluster_id_file.stat.exists
      block:
        - name: Generate Kafka cluster ID
          ansible.builtin.command: "{{ kafka_bin }}/kafka-storage.sh random-uuid"
          register: kafka_uuid
          changed_when: false

        - name: Save cluster ID
          ansible.builtin.copy:
            content: "{{ kafka_uuid.stdout }}"
            dest: "{{ kafka_cluster_id }}"
            mode: "0444"

    - name: Read existing cluster ID
      ansible.builtin.command: "cat {{ kafka_cluster_id }}"
      register: kafka_uuid
      changed_when: false

    - name: Configure Kafka broker
      ansible.builtin.command: >
        {{ kafka_bin }}/kafka-storage.sh format
        --standalone
        -t {{ kafka_uuid.stdout }}
        -c {{ kafka_config }}
      args:
        creates: "{{ kafka_logs }}/meta.properties"

    - name: Create kafka systemd service
      become: true
      ansible.builtin.copy:
        dest: /etc/systemd/system/kafka.service
        mode: '0644'
        content: |
          [Unit]
          Description=Apache Kafka Server
          After=network.target

          [Service]
          Type=simple
          User=vagrant
          Group=vagrant

          ExecStart={{ kafka_bin }}/kafka-server-start.sh {{ kafka_config }}
          ExecStop={{ kafka_bin }}/kafka-server-stop.sh

          Restart=on-failure
          RestartSec=10

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      become: true
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start Kafka
      become: true
      ansible.builtin.systemd:
        name: kafka
        enabled: true
        state: started


- name: Custom configurations
  hosts: all

  tasks:
    - name: Install apt packages
      become: true
      ansible.builtin.apt:
        name: jq
        state: present
