---
- name: Update and upgrade all packages
  hosts: all
  become: true

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist

- name: Install gnome desktop environment
  hosts: all
  become: true

  tasks:

    - name: Install apt packages
      apt:
        name:
          - gnome
          - gdm3
        state: latest

- name: Install Neovim
  hosts: all
  become: true
  vars:
    nvim_archive: nvim-linux-x86_64.tar.gz
    nvim_url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
    nvim_install_dir: /opt/nvim-linux-x86_64
  
  tasks:

    - name: Install common packages
      ansible.builtin.apt:
        name:
          - git
          - luarocks
        state: latest

    - name: Check if nvim is already installed
      ansible.builtin.stat:
        path: "{{ nvim_install_dir }}/bin/nvim"
      register: nvim_installed

    - name: Install Neovim
      block:

        - name: Download Neovim archive
          ansible.builtin.get_url:
            url: "{{ nvim_url }}"
            dest: "/tmp/{{ nvim_archive }}"
            mode: '0644'

        - name: Remove existing Neovim directory
          ansible.builtin.file:
            path: "{{ nvim_install_dir }}"
            state: absent

        - name: Extract Neovim archive
          ansible.builtin.unarchive:
            src: "/tmp/{{ nvim_archive }}"
            dest: /opt
            remote_src: yes

      when: not nvim_installed.stat.exists

    - name: Add Neovim to global PATH
      ansible.builtin.copy:
        dest: /etc/profile.d/nvim.sh
        content: 'export PATH="/opt/nvim-linux-x86_64/bin:$PATH"'
        mode: '0755'

- name: Configure Neovim
  hosts: all
  vars:
    nvim_config_src: /home/nemo/.config/nvim/

  tasks:

    - name: Copy configurations
      ansible.builtin.copy:
        src: "{{ nvim_config_src }}"
        dest: /home/vagrant/.config/nvim/
