---
- name: Install Go
  hosts: all

  vars:
    go_version: 1.26.2

  tasks:

    - name: Download Go
      ansible.builtin.get_url:
        url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: /tmp/go.tar.gz
        mode: "0500"

    - name: Extract Go
      become: true
      ansible.builtin.unarchive:
        src: /tmp/go.tar.gz
        dest: /usr/local
        remote_src: true

    - name: Add Go to PATH
      become: true
      ansible.builtin.copy:
        dest: /etc/profile.d/go.sh
        content: |
          export PATH=$PATH:/usr/local/go/bin
          export PATH=$PATH:/home/vagrant/go/bin
        mode: "0555"

- name: Install Docker
  hosts: all
  become: true

  tasks:

    - name: Set up Docker's apt repository
      ansible.builtin.script: ./docker.sh

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Create docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add docker group to user
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: true

    - name: Ensure docker.service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

- name: Install kind
  hosts: all

  tasks:

    - name: Install kind with go
      ansible.builtin.command: /usr/local/go/bin/go install sigs.k8s.io/kind@v0.31.0
      args:
        creates: /home/vagrant/go/bin/kind
