# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian-13"

  config.vm.provider("virtualbox") do |v|
    v.memory = 8192
    v.cpus = 2
  end

  config.vm.provision("ansible") do |ansible|
    ansible.playbook = "ansible.playbook.yml"
  end
end
