# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian-13"

  config.vm.provider("virtualbox") do |v|
    v.memory = 8192
    v.cpus = 2
  end

  (1..3).each do |i|
    config.vm.define("controlplane#{i}") do |node|
      node.vm.hostname = "controlplane#{i}"

      ipAddr = "192.168.56.#{20 + i}"
      node.vm.network("private_network", ip: ipAddr)
    end
  end

  (1..3).each do |i|
    config.vm.define("worker#{i}") do |node|
      node.vm.hostname = "worker#{i}"

      ipAddr = "192.168.56.#{23 + i}"
      node.vm.network("private_network", ip: ipAddr)
    end
  end
end
