# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian-13"

  config.vm.provider("virtualbox") do |v|
    v.memory = 8192
    v.cpus = 2
  end

  (1..3).each do |i|
    config.vm.define("controlplane#{i}") do |node|
      node.vm.hostname = "controlplane#{i}"

      ipAddr = "192.168.60.#{10 + i}"
      node.vm.network("private_network", ip: ipAddr, netmask: "255.255.252.0")
    end
  end

  (1..3).each do |i|
    config.vm.define("worker#{i}") do |node|
      node.vm.hostname = "worker#{i}"

      ipAddr = "192.168.60.#{110 + i}"
      node.vm.network("private_network", ip: ipAddr, netmask: "255.255.252.0")
    end
  end
end
