---
- name: Install npm dependencies
  hosts: all

  tasks:

    - name: Install apt dependencies
      become: true
      apt:
        name: npm
        update_cache: true

    - name: Copy workspace folder
      copy:
        src: ./workspace
        dest: /home/vagrant
        owner: vagrant

    - name: Install npm dependencies
      community.general.npm:
        path: /home/vagrant/workspace

- name: Install and configure Neovim
  hosts: all

  vars:
    nvim_archive: nvim-linux-x86_64.tar.gz
    nvim_url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
    nvim_install_dir: /opt/nvim-linux-x86_64
    nvim_config_src: /home/nemo/.config/nvim/
  
  tasks:

    - name: Install apt dependencies
      become: true
      ansible.builtin.apt:
        name:
          - git
          - luarocks
        update_cache: true

    - name: Check if nvim is already installed
      ansible.builtin.stat:
        path: "{{ nvim_install_dir }}/bin/nvim"
      register: nvim_installed

    - name: Install Neovim
      block:

        - name: Download Neovim archive
          ansible.builtin.get_url:
            url: "{{ nvim_url }}"
            dest: "/tmp/{{ nvim_archive }}"
            mode: '0644'

        - name: Remove existing Neovim directory
          ansible.builtin.file:
            path: "{{ nvim_install_dir }}"
            state: absent

        - name: Extract Neovim archive
          become: true
          ansible.builtin.unarchive:
            src: "/tmp/{{ nvim_archive }}"
            dest: /opt
            remote_src: yes

      when: not nvim_installed.stat.exists

    - name: Add Neovim to global PATH
      become: true
      ansible.builtin.copy:
        dest: /etc/profile.d/nvim.sh
        content: 'export PATH="/opt/nvim-linux-x86_64/bin:$PATH"'
        mode: '0755'

    - name: Copy configurations
      copy:
        src: "{{ nvim_config_src }}"
        dest: /home/vagrant/.config/nvim/
