# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian-13"

  config.vm.provider("virtualbox") do |v|
    v.memory = 32768
    v.cpus = 6
  end

  config.vm.provision("ansible") do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
