# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/ubuntu-24.04"

  config.vm.provider("virtualbox") do |v|
    v.memory = 32768
    v.cpus = 6
  end

  # Use bash as default shell for Vagrant user and enable SSH password authentication
  # WARNING: do not use "users:" to avoid overwrite 99_vagrant.cfg
  config.vm.cloud_init do |cloud_init|
    cloud_init.content_type = "text/cloud-config"
    cloud_init.inline = <<-EOF
    timezone: Europe/Rome
    package_update: True
    packages:
      - bash
    runcmd:
      - chsh -s /bin/bash vagrant
      - passwd -u vagrant
    ssh_pwauth: True
    EOF
  end
end
