---
- name: Install and configure Kafka
  hosts: all
  vars:
    kafka_url: https://downloads.apache.org/kafka/4.2.0/kafka_2.13-4.2.0.tgz
    kafka_archive: kafka_2.13-4.2.0.tgz

    kafka: /home/vagrant/kafka
    kafka_cluster_id: "{{ kafka }}/cluster.id"
    kafka_install_dir: "{{ kafka }}/kafka_2.13-4.2.0"
    kafka_bin: "{{ kafka_install_dir }}/bin"
    kafka_data: "{{ kafka }}/data"
    kafka_config: "{{ kafka }}/config"

  tasks:
    - name: Install apt dependencies
      become: true
      ansible.builtin.apt:
        name:
          - default-jdk
        state: latest
    
    - name: Create ~/kafka folder
      ansible.builtin.file:
        path: "{{ kafka_config }}"
        state: directory

    - name: Copy configuration folder
      ansible.builtin.copy:
        src: /vagrant/kafka/config/
        dest: "{{ kafka_config }}"
        remote_src: yes

    - name: Create data folders
      ansible.builtin.file:
        path: "{{ kafka_data }}/{{ item }}"
        state: directory
      loop:
        - kafka1
        - kafka2
        - kafka3
    
    - name: Check if Kafka is already installed
      ansible.builtin.stat:
        path: "{{ kafka_install_dir }}"
      register: kafka_installed

    - name: Download Kafka archive
      ansible.builtin.get_url:
        url: "{{ kafka_url }}"
        dest: "/tmp/{{ kafka_archive }}"
      when: not kafka_installed.stat.exists

    - name: Extract Kafka archive
      ansible.builtin.unarchive:
        src: "/tmp/{{ kafka_archive }}"
        dest: "{{ kafka }}"
        remote_src: yes
      when: not kafka_installed.stat.exists

    - name: Add Kafka to PATH
      become: true
      ansible.builtin.copy:
        dest: /etc/profile.d/kafka.sh
        content: 'export PATH={{ kafka_bin }}:"$PATH"'

    - name: Check if cluster ID exists
      ansible.builtin.stat:
        path: "{{ kafka_cluster_id }}"
      register: cluster_id_file

    - name: Generate Kafka cluster ID if not exist
      block:

        - name: Generate Kafka cluster ID
          ansible.builtin.command: "{{ kafka_bin }}/kafka-storage.sh random-uuid"
          register: kafka_uuid

        - name: Save cluster ID
          copy:
            content: "{{ kafka_uuid.stdout }}"
            dest: "{{ kafka_cluster_id }}"

      when: not cluster_id_file.stat.exists

    - name: Read existing cluster ID
      ansible.builtin.command: "cat {{ kafka_cluster_id }}"
      register: kafka_uuid

    - name: Initialize config directories
      ansible.builtin.command: >
        {{ kafka_bin}}/kafka-storage.sh format 
        -t {{ kafka_uuid.stdout }} 
        -c {{ kafka_config }}/kafka{{ item }}.properties
      args:
        creates: "{{ kafka_data }}/kafka{{ item }}/meta.properties"
      loop:
        - 1
        - 2
        - 3
