---
- name: Install Kafka and add to PATH
  hosts: all

  tasks:
    - name: Install apt dependencies
      become: true
      ansible.builtin.apt:
        name:
          - default-jdk
          - rsync
        update_cache: true
        cache_valid_time: 3600

    - name: Create ~/kafka folder
      ansible.builtin.file:
        path: "{{ kafka }}"
        state: directory
        mode: "0700"

    - name: Copy broker configuration file
      ansible.builtin.copy:
        src: "{{ kafka_config }}"
        dest: "{{ kafka_config_dest }}"
        mode: "0400"

    - name: Check if Kafka is already installed
      ansible.builtin.stat:
        path: "{{ kafka_install_dir }}"
      register: kafka_installed

    - name: Download Kafka archive
      ansible.builtin.get_url:
        url: "{{ kafka_url }}"
        dest: "/tmp/{{ kafka_archive }}"
        mode: "0700"
      when: not kafka_installed.stat.exists

    - name: Extract Kafka archive
      ansible.builtin.unarchive:
        src: "/tmp/{{ kafka_archive }}"
        dest: "{{ kafka }}"
        remote_src: true
      when: not kafka_installed.stat.exists

    - name: Add Kafka to PATH
      become: true
      ansible.builtin.copy:
        dest: /etc/profile.d/kafka.sh
        content: 'export PATH={{ kafka_bin }}:"$PATH"'
        mode: "0444"


- name: Configure Kafka nodes
  gather_facts: false
  hosts: all

  tasks:
    - name: Configure first Kafka node
      ansible.builtin.shell: >
        {{ kafka_bin }}/kafka-storage.sh format
        --cluster-id {{ kafka_cluster_uuid }}
        --standalone
        --config {{ kafka_config_dest }}
      when: inventory_hostname == "node-1"
      args:
        creates: "{{ kafka_data }}/meta.properties"

    - name: Configure other two Kafka nodes
      ansible.builtin.shell: >
        {{ kafka_bin }}/kafka-storage.sh format
        --cluster-id {{ kafka_cluster_uuid }}
        --config {{ kafka_config_dest }}
        --no-initial-controllers
      when: inventory_hostname != "node-1"
      args:
        creates: "{{ kafka_data }}/meta.properties"

    - name: Start the Kafka servers
      ansible.builtin.shell: >
        {{ kafka_bin }}/kafka-server-start.sh -daemon {{ kafka_config_dest }}
      changed_when: true

    - name: Wait for Kafka controller listener to be ready
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 9093
        delay: 5
        timeout: 10

    - name: Get quorum status
      ansible.builtin.shell: |
        set -o pipefail
        {{ kafka_bin }}/kafka-metadata-quorum.sh \
        --bootstrap-server {{ hostvars['node-1']['ansible_host'] }}:9092 \
        describe --status | grep "CurrentVoters" \
      changed_when: false
      register: quorum_status

    - name: Register node-2 and node-3 as controllers
      ansible.builtin.shell: >
        {{ kafka_bin }}/kafka-metadata-quorum.sh
        --command-config {{ kafka_config_dest }}
        --bootstrap-controller {{ hostvars['node-1']['ansible_host'] }}:9093
        add-controller
      changed_when: true
      when:
        - inventory_hostname != "node-1"
        - ansible_host not in quorum_status.stdout
