---
- name: Install Kafka and add to PATH
  hosts: all

  tasks:

    - name: Install apt dependencies
      become: true
      ansible.builtin.apt:
        name:
          - default-jdk

    - name: Create ~/kafka folder
      ansible.builtin.file:
        path: "{{ kafka }}"
        state: directory
        mode: "0700"

    - name: Copy broker configuration file
      ansible.builtin.copy:
        src: "{{ kafka_config }}"
        dest: "{{ kafka_config_dest }}"
        mode: "0400"

    - name: Check if Kafka is already installed
      ansible.builtin.stat:
        path: "{{ kafka_install_dir }}"
      register: kafka_installed

    - name: Download Kafka archive
      ansible.builtin.get_url:
        url: "{{ kafka_url }}"
        dest: "/tmp/{{ kafka_archive }}"
        mode: "0700"
      when: not kafka_installed.stat.exists

    - name: Extract Kafka archive
      ansible.builtin.unarchive:
        src: "/tmp/{{ kafka_archive }}"
        dest: "{{ kafka }}"
        remote_src: true
      when: not kafka_installed.stat.exists

    - name: Add Kafka to PATH
      become: true
      ansible.builtin.copy:
        dest: /etc/profile.d/kafka.sh
        content: 'export PATH={{ kafka_bin }}:"$PATH"'
        mode: "0444"

- name: Configure Kafka
  hosts: all

  tasks:

    - name: Clear data directory
      ansible.builtin.file:
        path: "{{ kafka_data }}"
        state: absent

    - name: Create data directory
      ansible.builtin.file:
        path: "{{ kafka_data }}"
        state: directory
        mode: "0700"

    - name: Configure Kafka brokers
      ansible.builtin.shell: >
        {{ kafka_bin }}/kafka-storage.sh format
        --cluster-id {{ kafka_cluster_uuid }}
        --config {{ kafka_config_dest }}
        --initial-controllers "
          0@192.168.56.11:9093:{{ kafka_controller_uuid_0 }},
          1@192.168.56.12:9093:{{ kafka_controller_uuid_1 }},
          2@192.168.56.13:9093:{{ kafka_controller_uuid_2 }}"
      args:
        creates: "{{ kafka_data }}/meta.properties"
