# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian-13"

  # Define three VMs with static IPs
  (1..3).each do |i|
    config.vm.define "node-#{i}" do |node|
      ipAddr = "192.168.56.#{10 + i}"
      node.vm.network "private_network", ip: ipAddr
    end
  end
end

