# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Define the base box for the VM
  config.vm.box = "debian-13"

  # Loop over the creation of three VMs
  (1..3).each do |i|
    # Use interpolation for the name of the VMs
    config.vm.define("node-#{i}") do |node|
      # Configure a private IP address for each VM
      ipAddr = "192.168.56.#{10 + i}"
      node.vm.network("private_network", ip: ipAddr)
    end
  end
end
