---
- name: Update and upgrade all packages
  hosts: all
  become: true

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

- name: Install and configure Neovim
  hosts: all

  vars:
    nvim_archive: nvim-linux-x86_64.tar.gz
    nvim_url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
    nvim_install_dir: /opt/nvim-linux-x86_64
    nvim_config_src: /home/nemo/.config/nvim/
  
  tasks:

    - name: Install apt dependencies
      become: true
      ansible.builtin.apt:
        name:
          - git
          - luarocks

    - name: Check if nvim is already installed
      ansible.builtin.stat:
        path: "{{ nvim_install_dir }}/bin/nvim"
      register: nvim_installed

    - name: Install Neovim
      block:

        - name: Download Neovim archive
          ansible.builtin.get_url:
            url: "{{ nvim_url }}"
            dest: "/tmp/{{ nvim_archive }}"
            mode: '0644'

        - name: Remove existing Neovim directory
          ansible.builtin.file:
            path: "{{ nvim_install_dir }}"
            state: absent

        - name: Extract Neovim archive
          become: true
          ansible.builtin.unarchive:
            src: "/tmp/{{ nvim_archive }}"
            dest: /opt
            remote_src: yes

      when: not nvim_installed.stat.exists

    - name: Add Neovim to global PATH
      become: true
      ansible.builtin.copy:
        dest: /etc/profile.d/nvim.sh
        content: 'export PATH="/opt/nvim-linux-x86_64/bin:$PATH"'
        mode: '0755'

    - name: Copy configurations
      copy:
        src: "{{ nvim_config_src }}"
        dest: /home/vagrant/.config/nvim/

- name: Install Neovim dependencies
  hosts: all

  vars:
    go_version: 1.26.2

  tasks:

    - name: Install apt dependencies
      become: true
      apt:
        name:
          - python3-pip
          - npm
          - ruby-full
          - php
          - composer
          - default-jdk
          - ripgrep
          - fd-find

    - name: Install Rust (rustup)
      shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
      args:
        creates: /home/vagrant/.cargo/bin/cargo

    - name: Add cargo to global PATH
      become: true
      copy:
        dest: /etc/profile.d/rust.sh
        content: 'export PATH="/home/vagrant/.cargo/bin:$PATH"'

    - name: Download Go
      get_url:
        url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: /tmp/go.tar.gz

    - name: Extract Go
      become: true
      unarchive:
        src: /tmp/go.tar.gz
        dest: /usr/local
        remote_src: yes

    - name: Add Go to PATH
      become: true
      copy:
        dest: /etc/profile.d/go.sh
        content: |
          export PATH=$PATH:/usr/local/go/bin

    - name: Install Julia
      shell: curl -fsSL https://install.julialang.org | sh -s -- -y
      args:
        creates: /home/vagrant/.juliaup/bin/julia
