Vagrant.configure("2") do |config|
  config.vm.box = "ntomic/trixie"
  config.vm.box_version = "1.0.0"

  config.vm.network("private_network", ip: "192.168.56.10")

  config.vm.provider("virtualbox") do |v|
    v.memory = 8192
    v.cpus = 4
  end

  config.vm.provision("ansible") do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
